// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSqUxoUejcdciJhC97IP6xP51SSpK81wc',
    appId: '1:215219931196:web:55554f5f0194ec06f9db39',
    messagingSenderId: '215219931196',
    projectId: 'finance-tracker-c9b69',
    authDomain: 'finance-tracker-c9b69.firebaseapp.com',
    storageBucket: 'finance-tracker-c9b69.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6HyJSWOBNAnA-EuYYR5MufsOfmNWN9rM',
    appId: '1:215219931196:android:e9cec93aba4c9a5af9db39',
    messagingSenderId: '215219931196',
    projectId: 'finance-tracker-c9b69',
    storageBucket: 'finance-tracker-c9b69.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8paAxDnLGUEMYxnY6lN0lbUAVsL6rS_w',
    appId: '1:215219931196:ios:c535e719ee9435fff9db39',
    messagingSenderId: '215219931196',
    projectId: 'finance-tracker-c9b69',
    storageBucket: 'finance-tracker-c9b69.appspot.com',
    iosBundleId: 'com.example.financeTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8paAxDnLGUEMYxnY6lN0lbUAVsL6rS_w',
    appId: '1:215219931196:ios:82456db9c92303c3f9db39',
    messagingSenderId: '215219931196',
    projectId: 'finance-tracker-c9b69',
    storageBucket: 'finance-tracker-c9b69.appspot.com',
    iosBundleId: 'com.example.financeTracker.RunnerTests',
  );
}
